spring.application.name=Geopetro Desktop
spring.main.web-application-type=none

# Desktop
app.title=Geopetro Desktop
app.version=0.1.0

# H2 database (caminho absoluto no home do usuario - evita problemas de permissao em C:\Program Files)
spring.datasource.url=jdbc:h2:${user.home}/.geopetro-io/data/sonda_geopetro;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
