# -*- coding: utf-8 -*-
"""Texto do documento de decisoes de arquitetura em pt-BR e es-CO.

Fonte: specs/SDD (system-overview, braserv-core, websocket-realtime, mqtt-telemetria,
cards-configuraveis, alarmes, configuracao-da-estacao) e deploy/README.md, em 2026-10-07.
"""

PT = {
    "arquivo": "Decisoes de Arquitetura - GeopetroIO (pt-BR).pdf",
    "titulo_doc": "Decisões de Arquitetura",
    "sobretitulo": "GEOPETROIO · BRASERV PETRÓLEO",
    "subtitulo": "Como o sistema está organizado e por que foi feito assim",
    "rodape": "GeopetroIO · Decisões de Arquitetura",
    "pagina": "Página",
    "versao": "Versão de outubro de 2026 · Português (Brasil)",
    "equipe": "Braserv Petróleo · Desenvolvimento e Automação",
    "sumario": "Sumário",
    "apresentacao": [
        "<b>Para quem é este documento.</b> Equipe técnica que desenvolve, implanta ou mantém o GeopetroIO. "
        "Ele resume as decisões que dão forma ao sistema e o motivo de cada uma.",
        "<b>Como ler.</b> A parte 1 mostra o conjunto e o fluxo de dados. A parte 2 traz cada decisão no formato "
        "contexto, decisão e consequências. A parte 3 lista riscos aceitos e pendências. Os detalhes vivem nas "
        "specs do repositório, indicadas em cada decisão.",
        "<b>Situação.</b> Em outubro de 2026 o sistema ainda não está em produção. Por isso algumas mudanças "
        "entraram sem migração gradual nem compatibilidade com nomes antigos.",
    ],
    "h_visao": "1. Visão geral",
    "visao_intro": "O GeopetroIO coleta dados de unidades em campo, como sondas, unidades de bombeio e "
                   "cimentação, e os entrega à supervisão remota e ao cliente. São seis aplicações independentes.",
    "cab_apps": ["Aplicação", "Tecnologia", "Papel"],
    "apps": [
        ["Braserv-Core", "Spring Boot · Java 21", "Identidade, login, tokens e cadastro organizacional: usuários, empresas, regionais, setores e unidades."],
        ["Geopetro-Backend", "Spring Boot · Java 21", "Monitoramento, tempo real, alarmes, configuração de cards e simulador de cimentação."],
        ["Geopetro-Front", "Angular 21 · Taiga UI", "Aplicação web para cadastro, monitoramento, alarmes, simuladores e relatórios."],
        ["Geopetro-Desktop", "JavaFX 21 · Spring Boot", "Agente de borda no PC da unidade. Lê o CLP LOGO!, mostra o painel local e publica telemetria."],
        ["Geopetro-Telemetria", "Spring Boot · InfluxDB", "Consome o MQTT, grava as séries no InfluxDB e responde consultas de histórico ao Backend."],
        ["Braserv-Horus", "JavaFX 21 · Gradle", "Aplicação de cimentação autônoma. Lê o CLP da bomba e gera a carta de operação em PDF."],
    ],
    "h_fluxo": "Fluxo de arquitetura",
    "fluxo_intro": "O diagrama mostra a implantação em duas máquinas virtuais. Os números nas setas "
                   "correspondem à tabela logo abaixo.",
    "cap_arq": "Figura 1 — Fluxo de arquitetura do GeopetroIO.",
    "cab_fluxo": ["Nº", "Origem e destino", "Protocolo", "Para quê"],
    "fluxo": [
        ["1", "CLP LOGO! → PC da unidade", "S7 · TCP 102", "O Geopetro-Desktop, no PC da unidade, lê a memória V do LOGO! a cada ciclo, normalmente 1 s, e converte cada valor conforme o tipo do card."],
        ["2", "PC → Mosquitto", "MQTT · QoS 1", "Histórico. Uma mensagem por ciclo no tópico telemetria/{idUnidade}/batch."],
        ["3", "Telemetria → InfluxDB", "HTTP · lote", "Gravação assíncrona em lotes de 500 pontos ou 1 s, em UTC."],
        ["4", "PC → nginx", "HTTPS · WebSocket", "Login no Core, envio do tempo real por STOMP e recebimento do documento de cards."],
        ["5", "Navegador → nginx", "HTTPS · WSS", "Telas web e assinatura do tempo real."],
        ["6", "nginx → Core", "HTTP", "Login, usuários, empresas, regionais, setores, unidades e clientes de serviço."],
        ["7", "nginx → Backend", "HTTP · STOMP", "Monitoramento, alarmes, simulador e /ws."],
        ["8", "Backend ↔ Core", "HTTP interno", "Chaves JWKS, acesso atual do usuário, catálogo de unidades e vínculos antes de excluir."],
        ["9", "Backend → Telemetria", "HTTP interno", "Consulta de séries históricas. O Front nunca chama a Telemetria."],
        ["10", "Core e Backend → MySQL", "JDBC", "Mesmo servidor MySQL, databases e usuários separados."],
        ["11", "CLP LOGO! → Horus", "S7 · TCP 102", "Cimentação autônoma, sem integração com as demais aplicações."],
    ],
    "diag_arq": {
        "campo": "CAMPO · UNIDADE", "autonomo": "AUTÔNOMO", "vm1": "VM-1 · TRANSACIONAL",
        "vm2": "VM-2 · TELEMETRIA", "navegador": "Navegador", "origem_unica": "proxy · origem única",
        "backend_l": ["monitoramento", "tempo real · alarmes", "cards · simulador"],
        "core_l": ["login · tokens RS256", "cadastros · unidades", "JWKS"],
        "broker": "broker MQTT", "tel_l": "ingestão · séries", "influx_l": "histórico",
        "clp_s7": "CLP Siemens LOGO!", "clp_logo": "CLP Siemens LOGO!",
        "pc": "PC DA UNIDADE", "saida_ws": "WebSocket", "saida_mqtt": "MQTT",
        "desk_l": ["leitura e conversão", "painel local", "alarme da estação", "H2 local", "cache de cards"],
        "horus_l": ["Cimentação", "carta de operação", "em PDF"],
        "leg_hist": "histórico", "leg_pub": "acesso público pelo proxy", "leg_int": "chamadas internas",
    },
    "h_borda": "Dentro do Desktop",
    "borda_intro": "Uma thread virtual lê o LOGO!, converte os valores e entrega a leitura para quatro destinos. Nenhum destino "
                   "bloqueia a leitura nem os outros destinos.",
    "cap_borda": "Figura 2 — Como a leitura se divide dentro do Geopetro-Desktop.",
    "diag_borda": {
        "clp": "CLP", "leitor": "plc-reader", "leitor_sub": "1 leitura por ciclo",
        "borda_linhas": [
            ("Fila de 3600", "MQTT", "não perde: envia o acumulado"),
            ("Último valor", "Tempo real", "envia só o mais recente"),
            ("Gravação local", "H2 em arquivo", "registro completo"),
            ("Tela JavaFX", "Painel e alarme", "funciona sem rede"),
        ],
    },
    "h_decisoes": "2. Decisões",
    "decisoes_intro": "Cada decisão traz o problema que a motivou, o que foi decidido e o que isso "
                      "provoca no sistema. As referências apontam para as specs em specs/SDD.",
    "rot": ["Contexto", "Decisão", "Consequências", "Referências"],
    "decisoes": [
        {"t": "Monorepo com aplicações independentes",
         "c": "O sistema reúne coleta em campo, monitoramento web, histórico e simulação. Cada parte tem ritmo de entrega e forma de implantação diferentes.",
         "d": "Seis aplicações implantáveis em apps/, cada uma com build e Dockerfile próprios. O Braserv-Horus continua separado e não será absorvido pelo Geopetro-Desktop.",
         "q": ["Cada aplicação é construída e implantada sozinha.",
               "A duplicação entre os dois desktops é aceita de propósito (DT-010).",
               "Quatro classes de base são copiadas entre Core e Backend. Uma biblioteca comum só será extraída quando um terceiro serviço precisar."],
         "r": "README.md · software/system-overview.md · software/technical-debt.md"},
        {"t": "Braserv-Core é dono da identidade e do cadastro organizacional",
         "c": "Usuário, empresa, regional, setor e unidade servem a outros sistemas da Braserv, não só ao GeopetroIO.",
         "d": "Esses cadastros e o login pertencem ao Braserv-Core. O Backend não copia tabelas e lê pelo contrato interno do Core. Cada serviço tem database e usuário próprios no mesmo servidor MySQL: braserv_core e geopetro_io.",
         "q": ["Um sistema novo reaproveita login e estrutura sem depender do Backend.",
               "No Backend, unidade_id é referência lógica, sem chave estrangeira entre databases.",
               "Excluir uma unidade exige confirmação do Backend e da Telemetria. Sem resposta em 5 s, a exclusão é recusada. Unidade já usada é inativada, nunca excluída."],
         "r": "software/backend/braserv-core.md · RN-115 a RN-119"},
        {"t": "Só o Core emite tokens, assinados com RS256",
         "c": "Vários serviços precisam confiar na identidade do usuário sem compartilhar um segredo.",
         "d": "O Core assina com a chave privada e publica as chaves públicas no JWKS. Token de pessoa vale 1 h e token de serviço vale 15 min. O campo tipo impede que token de pessoa abra rota interna e que token de serviço abra rota pública. O Backend consulta no Core o acesso atual do usuário, com cache de 10 s.",
         "q": ["Nenhum consumidor guarda segredo de assinatura.",
               "Desativar um usuário corta o acesso em até 10 s.",
               "Com o Core fora do ar, o Backend usa o último acesso conhecido por até 5 min e depois nega. É o custo aceito para que um reinício do Core não derrube o tempo real.",
               "A revogação individual de token continua pendente (SEC-008)."],
         "r": "software/backend/braserv-core.md §6 · software/apis/braserv-core.md"},
        {"t": "Uma origem única pelo proxy",
         "c": "O navegador fala com dois serviços, e as rotas internas não podem ficar expostas.",
         "d": "O nginx do Front publica uma única origem. Identidade e cadastros vão ao Core. Monitoramento, simulador e /ws vão ao Backend. As rotas /internal/** e /.well-known/** não são publicadas. O Front nunca chama a Telemetria.",
         "q": ["Não há CORS entre serviços no navegador.",
               "A superfície pública fica menor.",
               "O Backend valida o acesso à unidade antes de consultar a Telemetria."],
         "r": "software/system-overview.md §3"},
        {"t": "Dois caminhos independentes para a telemetria",
         "c": "O histórico não pode perder leituras. O tempo real só precisa do estado mais recente.",
         "d": "MQTT leva o histórico até a Telemetria e o InfluxDB. WebSocket com STOMP leva o estado atual ao Backend, que o repassa ao Front sem gravar. No Desktop, o MQTT usa uma fila de 3600 leituras e o tempo real guarda só o último valor. Cada caminho tem seu próprio worker em thread virtual.",
         "q": ["A falha de um caminho não afeta o outro nem a leitura do CLP.",
               "A fila cobre cerca de uma hora de broker fora do ar. O banco H2 local guarda o registro completo.",
               "Ao reconectar, o tempo real envia só o estado mais recente.",
               "Cada caminho pode ser desligado na engrenagem da estação."],
         "r": "software/apis/websocket-realtime.md · software/mqtt/mqtt-telemetria.md"},
        {"t": "MQTT em lote com mensagem que se descreve",
         "c": "Uma mensagem por sensor multiplicaria o volume, e brokers gerenciados cobram por mensagem.",
         "d": "Uma mensagem por ciclo, QoS 1, no tópico telemetria/{idUnidade}/batch. Cada leitura carrega tipo, série e endereço, então não existe catálogo central. Só o Desktop publica e só a Telemetria consome. O Backend saiu do broker.",
         "q": ["O volume é cerca de 5 vezes menor que o formato por sensor.",
               "Leitura sem valor, como peso ainda sem calibração, não é publicada.",
               "Pendentes: autenticação no broker (SEC-009) e buffer de contingência no produtor."],
         "r": "software/mqtt/mqtt-telemetria.md"},
        {"t": "Serviço de Telemetria com InfluxDB",
         "c": "A escrita é contínua, 24 horas por dia, e as consultas pedem horas de dados a cada 1 s.",
         "d": "Um serviço próprio grava as séries no InfluxDB em lotes assíncronos e sempre em UTC. Consultas acima de 2000 pontos por série são reduzidas. O broker fora do ar não impede o serviço de subir.",
         "q": ["A carga de escrita fica separada do MySQL transacional.",
               "A tela de histórico recebe volume controlado mesmo em janelas longas.",
               "A Telemetria não conhece usuários. Quem controla acesso é o Backend."],
         "r": "apps/geopetro-telemetria/specs · software/apis/rest-monitoramento.md"},
        {"t": "Como a unidade é identificada",
         "c": "A web precisa de um identificador estável. O contrato de coleta já usava o nome da unidade.",
         "d": "O cadastro se chama Unidade em todo o sistema. Web, REST e WebSocket usam o id numérico. MQTT e InfluxDB usam o nome da unidade como chave. O Backend traduz um no outro antes de consultar a Telemetria.",
         "q": ["O Front trabalha com um único identificador.",
               "Renomear uma unidade corta a série histórica em duas. É o risco de maior custo registrado (RN-018)."],
         "r": "RN-018 · RN-119 · software/backend/braserv-core.md §9"},
        {"t": "Desktop como agente de borda dirigido por configuração",
         "c": "Cinco grandezas fixas no código impediam instrumentar equipamentos que não fossem sonda.",
         "d": "Cada unidade tem um documento de cards com a conexão do CLP e a lista de cards, cada um com tipo e endereço. Ele é editado só no Desktop, por ADMIN ou SUPORTE, guardado no Backend com número de revisão, entregue pelo canal STOMP /cards e mantido em cache em disco. Há seis tipos fechados. A leitura é feita em bloco, uma faixa do DB por ciclo.",
         "q": ["Instrumentar um equipamento novo vira cadastro, não projeto.",
               "Unidade sem cards não lê nem publica (RN-088).",
               "Duas edições simultâneas são recusadas pela revisão, com erro 409.",
               "Ao copiar de outra unidade, o IP do CLP não é copiado."],
         "r": "negocio/requisitos/cards-configuraveis.md · software/apis/configuracao-sonda.md"},
        {"t": "Identidade estável do card",
         "c": "O id do card vira tag no InfluxDB, com retenção de 5 anos. Tag com valores livres degrada o banco.",
         "d": "O id é gerado no formato TIPO_NN, nunca muda e não é reaproveitado. O nome é só rótulo de tela. Card não se exclui, se desativa. O limite é de 100 cards por unidade.",
         "q": ["A quantidade de tags no InfluxDB fica sob controle.",
               "Toda série antiga continua tendo um card que explica o que ela mede."],
         "r": "RN-081 · RN-091 · software/mqtt/mqtt-telemetria.md §4"},
        {"t": "Calibração fica na estação",
         "c": "Geometria de peso e de chave hidráulica são medidas em campo, na própria unidade.",
         "d": "A calibração de peso e torque fica no computador da unidade, em config/calibracao-cards.json, separada pelo id do card. O range do transmissor fica no documento da unidade.",
         "q": ["Os valores medidos em campo não trafegam pela rede.",
               "Trocar o computador exige refazer ou copiar a calibração."],
         "r": "negocio/requisitos/cards-configuraveis.md §10b"},
        {"t": "O servidor registra o alarme e a estação sinaliza",
         "c": "Supervisão e cliente precisam de um histórico único. A equipe na unidade precisa de alarme mesmo sem rede.",
         "d": "O Backend é o único produtor do histórico de alarmes. Ele avalia os limites remotos sobre o canal de tempo real. O alarme é a única parte do sistema orientada a eventos: cada episódio é uma sequência só de inclusões. A estação tem limites locais próprios, funciona sem rede e sem login, e não gera evento.",
         "q": ["Existe uma única fonte de verdade para o histórico de alarmes.",
               "Unidade com tempo real caído, ou card invisível, não alarma no servidor mesmo publicando MQTT.",
               "O alarme local só chega à frota com o auto-update do Desktop, que ainda não existe."],
         "r": "negocio/requisitos/alarmes.md · negocio/requisitos/configuracao-da-estacao.md"},
        {"t": "Configuração restrita, com sessão só em memória",
         "c": "Acertar endereço, rack e slot exige estar na unidade. Existe uma credencial de serviço comum à frota.",
         "d": "Configurar exige ADMIN ou SUPORTE autenticado online. A sessão vive em memória e não é gravada em disco. Sem login, o Desktop continua lendo, publicando e alarmando.",
         "q": ["Nenhuma credencial extra fica gravada na borda (SEC-011).",
               "Configurar uma estação exige internet."],
         "r": "RN-086 · negocio/requisitos/configuracao-da-estacao.md §5"},
        {"t": "Implantação separada por caminho de dados",
         "c": "A ingestão escreve sem parar e recebe conexões das unidades. A parte web é intermitente e guarda o cadastro de usuários.",
         "d": "Duas máquinas virtuais. A transacional tem Front, Core, Backend e MySQL. A de telemetria tem Mosquitto, Telemetria e InfluxDB. Existe também uma alternativa em máquina única, com Caddy e TLS automático. Os bancos MySQL são versionados com Flyway e validados na subida.",
         "q": ["Uma falha na web não interrompe a ingestão.",
               "Cada lado escala de forma independente.",
               "O InfluxDB fica junto do consumidor, então a escrita contínua não atravessa a rede. Entre as máquinas só passa a consulta REST."],
         "r": "deploy/README.md · deploy/vm-unica/README.md"},
        {"t": "Arquitetura hexagonal por módulo",
         "c": "Core e Backend têm vários domínios e dependem um do outro por rede.",
         "d": "Core e Backend são projetos Maven com um módulo por domínio, organizados em portas e adaptadores. A integração entre serviços passa por portas, como AcessoDoUsuarioPort e CatalogoDeUnidadesPort.",
         "q": ["Trocar um adaptador, como o cliente HTTP do Core, não toca a regra de negócio.",
               "Os testes de domínio rodam sem rede."],
         "r": "software/backend/braserv-core.md §7 e §10"},
    ],
    "h_riscos": "3. Riscos aceitos e pendências",
    "riscos_intro": "Estes pontos são conhecidos e foram aceitos ou estão aguardando decisão.",
    "cab_riscos": ["Ponto", "Efeito", "Situação"],
    "riscos": [
        ["Broker STOMP em memória", "Com duas instâncias do Backend, o tempo real não passa de uma para a outra.", "Aceito enquanto houver uma instância. Solução prevista: broker externo."],
        ["Broker MQTT sem autenticação", "Qualquer cliente na rede pode publicar no tópico de telemetria.", "Pendente (SEC-009)."],
        ["Nome da unidade como chave", "Renomear corta a série histórica.", "Risco aceito (RN-018)."],
        ["Sem auto-update do Desktop", "Correções só chegam às unidades por visita.", "Pendente."],
        ["Buffer de contingência MQTT", "Broker fora por mais de uma hora descarta as leituras mais antigas da fila.", "Pendente (P-07). O H2 local mantém o registro."],
        ["Token sem revogação individual", "Um token vazado vale até expirar.", "Pendente (SEC-008)."],
        ["Repositórios dentro do OneDrive", "A sincronização já corrompeu um repositório Git.", "Pendente (DT-004)."],
    ],
    "h_onde": "Onde aprofundar",
    "onde": [
        ["Visão do sistema", "specs/SDD/software/system-overview.md"],
        ["Braserv-Core", "specs/SDD/software/backend/braserv-core.md"],
        ["Tempo real", "specs/SDD/software/apis/websocket-realtime.md"],
        ["Telemetria MQTT", "specs/SDD/software/mqtt/mqtt-telemetria.md"],
        ["Cards configuráveis", "specs/SDD/negocio/requisitos/cards-configuraveis.md"],
        ["Alarmes", "specs/SDD/negocio/requisitos/alarmes.md"],
        ["Implantação", "deploy/README.md"],
        ["Regras e pendências", "specs/SDD/negocio/regras/business-rules.md · requisitos/open-questions.md"],
    ],
    "cab_onde": ["Assunto", "Documento"],
}

ES = {
    "arquivo": "Decisiones de Arquitectura - GeopetroIO (es-CO).pdf",
    "titulo_doc": "Decisiones de Arquitectura",
    "sobretitulo": "GEOPETROIO · BRASERV PETRÓLEO",
    "subtitulo": "Cómo está organizado el sistema y por qué se hizo así",
    "rodape": "GeopetroIO · Decisiones de Arquitectura",
    "pagina": "Página",
    "versao": "Versión de octubre de 2026 · Español (Colombia)",
    "equipe": "Braserv Petróleo · Desarrollo y Automatización",
    "sumario": "Contenido",
    "apresentacao": [
        "<b>Para quién es este documento.</b> El equipo técnico que desarrolla, despliega o mantiene GeopetroIO. "
        "Resume las decisiones que dan forma al sistema y el motivo de cada una.",
        "<b>Cómo leerlo.</b> La parte 1 muestra el conjunto y el flujo de datos. La parte 2 presenta cada decisión "
        "en el formato contexto, decisión y consecuencias. La parte 3 lista los riesgos aceptados y los pendientes. "
        "Los detalles están en las specs del repositorio, indicadas en cada decisión.",
        "<b>Situación.</b> En octubre de 2026 el sistema todavía no está en producción. Por eso algunos cambios "
        "entraron sin migración gradual ni compatibilidad con nombres anteriores.",
        "<b>Nota sobre los nombres.</b> Las pantallas y el código están en portugués. Cuando aparece un nombre "
        "propio del sistema, se mantiene como está, por ejemplo <i>card</i> (tarjeta) o <i>Unidade</i> (unidad).",
    ],
    "h_visao": "1. Visión general",
    "visao_intro": "GeopetroIO recoge datos de unidades en campo, como taladros, unidades de bombeo y "
                   "cementación, y los entrega a la supervisión remota y al cliente. Son seis aplicaciones independientes.",
    "cab_apps": ["Aplicación", "Tecnología", "Función"],
    "apps": [
        ["Braserv-Core", "Spring Boot · Java 21", "Identidad, inicio de sesión, tokens y registro organizacional: usuarios, empresas, regionales, sectores y unidades."],
        ["Geopetro-Backend", "Spring Boot · Java 21", "Monitoreo, tiempo real, alarmas, configuración de tarjetas y simulador de cementación."],
        ["Geopetro-Front", "Angular 21 · Taiga UI", "Aplicación web para registros, monitoreo, alarmas, simuladores e informes."],
        ["Geopetro-Desktop", "JavaFX 21 · Spring Boot", "Agente de borde en el PC de la unidad. Lee el PLC LOGO!, muestra el panel local y publica la telemetría."],
        ["Geopetro-Telemetria", "Spring Boot · InfluxDB", "Consume MQTT, guarda las series en InfluxDB y responde las consultas de histórico al Backend."],
        ["Braserv-Horus", "JavaFX 21 · Gradle", "Aplicación de cementación autónoma. Lee el PLC de la bomba y genera la carta de operación en PDF."],
    ],
    "h_fluxo": "Flujo de arquitectura",
    "fluxo_intro": "El diagrama muestra el despliegue en dos máquinas virtuales. Los números de las flechas "
                   "corresponden a la tabla de abajo.",
    "cap_arq": "Figura 1 — Flujo de arquitectura de GeopetroIO.",
    "cab_fluxo": ["N.º", "Origen y destino", "Protocolo", "Para qué"],
    "fluxo": [
        ["1", "PLC LOGO! → PC de la unidad", "S7 · TCP 102", "Geopetro-Desktop, en el PC de la unidad, lee la memoria V del LOGO! en cada ciclo, normalmente 1 s, y convierte cada valor según el tipo de tarjeta."],
        ["2", "PC → Mosquitto", "MQTT · QoS 1", "Histórico. Un mensaje por ciclo en el tópico telemetria/{idUnidade}/batch."],
        ["3", "Telemetría → InfluxDB", "HTTP · lote", "Escritura asíncrona en lotes de 500 puntos o 1 s, en UTC."],
        ["4", "PC → nginx", "HTTPS · WebSocket", "Inicio de sesión en el Core, envío del tiempo real por STOMP y recepción del documento de tarjetas."],
        ["5", "Navegador → nginx", "HTTPS · WSS", "Pantallas web y suscripción al tiempo real."],
        ["6", "nginx → Core", "HTTP", "Inicio de sesión, usuarios, empresas, regionales, sectores, unidades y clientes de servicio."],
        ["7", "nginx → Backend", "HTTP · STOMP", "Monitoreo, alarmas, simulador y /ws."],
        ["8", "Backend ↔ Core", "HTTP interno", "Llaves JWKS, acceso actual del usuario, catálogo de unidades y vínculos antes de eliminar."],
        ["9", "Backend → Telemetría", "HTTP interno", "Consulta de series históricas. El Front nunca llama a la Telemetría."],
        ["10", "Core y Backend → MySQL", "JDBC", "Mismo servidor MySQL, bases de datos y usuarios separados."],
        ["11", "PLC LOGO! → Horus", "S7 · TCP 102", "Cementación autónoma, sin integración con las demás aplicaciones."],
    ],
    "diag_arq": {
        "campo": "CAMPO · UNIDAD", "autonomo": "AUTÓNOMO", "vm1": "VM-1 · TRANSACCIONAL",
        "vm2": "VM-2 · TELEMETRÍA", "navegador": "Navegador", "origem_unica": "proxy · origen única",
        "backend_l": ["monitoreo", "tiempo real · alarmas", "tarjetas · simulador"],
        "core_l": ["login · tokens RS256", "registros · unidades", "JWKS"],
        "broker": "broker MQTT", "tel_l": "ingesta · series", "influx_l": "histórico",
        "clp_s7": "PLC Siemens LOGO!", "clp_logo": "PLC Siemens LOGO!",
        "pc": "PC DE LA UNIDAD", "saida_ws": "WebSocket", "saida_mqtt": "MQTT",
        "desk_l": ["lectura y conversión", "panel local", "alarma de la estación", "H2 local", "caché de tarjetas"],
        "horus_l": ["Cementación", "carta de operación", "en PDF"],
        "leg_hist": "histórico", "leg_pub": "acceso público por el proxy", "leg_int": "llamadas internas",
    },
    "h_borda": "Dentro del Desktop",
    "borda_intro": "Un hilo virtual lee el LOGO!, convierte los valores y entrega la lectura a cuatro destinos. Ningún destino "
                   "bloquea la lectura ni a los demás destinos.",
    "cap_borda": "Figura 2 — Cómo se reparte la lectura dentro de Geopetro-Desktop.",
    "diag_borda": {
        "clp": "PLC", "leitor": "plc-reader", "leitor_sub": "1 lectura por ciclo",
        "borda_linhas": [
            ("Cola de 3600", "MQTT", "no pierde: envía lo acumulado"),
            ("Último valor", "Tiempo real", "envía solo lo más reciente"),
            ("Grabación local", "H2 en archivo", "registro completo"),
            ("Pantalla JavaFX", "Panel y alarma", "funciona sin red"),
        ],
    },
    "h_decisoes": "2. Decisiones",
    "decisoes_intro": "Cada decisión presenta el problema que la motivó, lo que se decidió y lo que eso "
                      "provoca en el sistema. Las referencias apuntan a las specs en specs/SDD.",
    "rot": ["Contexto", "Decisión", "Consecuencias", "Referencias"],
    "decisoes": [
        {"t": "Monorepo con aplicaciones independientes",
         "c": "El sistema reúne recolección en campo, monitoreo web, histórico y simulación. Cada parte tiene un ritmo de entrega y una forma de despliegue diferentes.",
         "d": "Seis aplicaciones desplegables en apps/, cada una con su propio build y Dockerfile. Braserv-Horus sigue separado y no será absorbido por Geopetro-Desktop.",
         "q": ["Cada aplicación se construye y se despliega por sí sola.",
               "La duplicación entre los dos desktops se acepta a propósito (DT-010).",
               "Cuatro clases base se copian entre Core y Backend. Una biblioteca común solo se extraerá cuando un tercer servicio la necesite."],
         "r": "README.md · software/system-overview.md · software/technical-debt.md"},
        {"t": "Braserv-Core es dueño de la identidad y del registro organizacional",
         "c": "Usuario, empresa, regional, sector y unidad sirven a otros sistemas de Braserv, no solo a GeopetroIO.",
         "d": "Esos registros y el inicio de sesión pertenecen a Braserv-Core. El Backend no copia tablas y lee mediante el contrato interno del Core. Cada servicio tiene su propia base de datos y su propio usuario en el mismo servidor MySQL: braserv_core y geopetro_io.",
         "q": ["Un sistema nuevo reutiliza el inicio de sesión y la estructura sin depender del Backend.",
               "En el Backend, unidade_id es una referencia lógica, sin llave foránea entre bases de datos.",
               "Eliminar una unidad exige confirmación del Backend y de la Telemetría. Sin respuesta en 5 s, la eliminación se rechaza. Una unidad ya usada se inactiva, nunca se elimina."],
         "r": "software/backend/braserv-core.md · RN-115 a RN-119"},
        {"t": "Solo el Core emite tokens, firmados con RS256",
         "c": "Varios servicios necesitan confiar en la identidad del usuario sin compartir un secreto.",
         "d": "El Core firma con la llave privada y publica las llaves públicas en el JWKS. El token de persona vale 1 h y el token de servicio vale 15 min. El campo tipo impide que un token de persona abra una ruta interna y que un token de servicio abra una ruta pública. El Backend consulta en el Core el acceso actual del usuario, con caché de 10 s.",
         "q": ["Ningún consumidor guarda un secreto de firma.",
               "Desactivar un usuario corta el acceso en máximo 10 s.",
               "Si el Core se cae, el Backend usa el último acceso conocido hasta por 5 min y después lo niega. Es el costo aceptado para que un reinicio del Core no tumbe el tiempo real.",
               "La revocación individual de tokens sigue pendiente (SEC-008)."],
         "r": "software/backend/braserv-core.md §6 · software/apis/braserv-core.md"},
        {"t": "Un solo origen a través del proxy",
         "c": "El navegador habla con dos servicios, y las rutas internas no pueden quedar expuestas.",
         "d": "El nginx del Front publica un único origen. Identidad y registros van al Core. Monitoreo, simulador y /ws van al Backend. Las rutas /internal/** y /.well-known/** no se publican. El Front nunca llama a la Telemetría.",
         "q": ["No hay CORS entre servicios en el navegador.",
               "La superficie pública es más pequeña.",
               "El Backend valida el acceso a la unidad antes de consultar la Telemetría."],
         "r": "software/system-overview.md §3"},
        {"t": "Dos caminos independientes para la telemetría",
         "c": "El histórico no puede perder lecturas. El tiempo real solo necesita el estado más reciente.",
         "d": "MQTT lleva el histórico hasta la Telemetría e InfluxDB. WebSocket con STOMP lleva el estado actual al Backend, que lo reenvía al Front sin guardarlo. En el Desktop, MQTT usa una cola de 3600 lecturas y el tiempo real guarda solo el último valor. Cada camino tiene su propio worker en un hilo virtual.",
         "q": ["La falla de un camino no afecta al otro ni a la lectura del PLC.",
               "La cola cubre cerca de una hora de broker caído. La base H2 local guarda el registro completo.",
               "Al reconectarse, el tiempo real envía solo el estado más reciente.",
               "Cada camino se puede apagar en el engranaje de configuración de la estación."],
         "r": "software/apis/websocket-realtime.md · software/mqtt/mqtt-telemetria.md"},
        {"t": "MQTT por lotes con mensaje autodescriptivo",
         "c": "Un mensaje por sensor multiplicaría el volumen, y los brokers administrados cobran por mensaje.",
         "d": "Un mensaje por ciclo, QoS 1, en el tópico telemetria/{idUnidade}/batch. Cada lectura lleva tipo, serie y dirección, así que no existe un catálogo central. Solo el Desktop publica y solo la Telemetría consume. El Backend salió del broker.",
         "q": ["El volumen es cerca de 5 veces menor que el formato por sensor.",
               "Una lectura sin valor, como un peso aún sin calibrar, no se publica.",
               "Pendientes: autenticación en el broker (SEC-009) y búfer de contingencia en el productor."],
         "r": "software/mqtt/mqtt-telemetria.md"},
        {"t": "Servicio de Telemetría con InfluxDB",
         "c": "La escritura es continua, las 24 horas, y las consultas piden horas de datos a 1 s.",
         "d": "Un servicio propio guarda las series en InfluxDB en lotes asíncronos y siempre en UTC. Las consultas de más de 2000 puntos por serie se reducen. Un broker caído no impide que el servicio arranque.",
         "q": ["La carga de escritura queda separada del MySQL transaccional.",
               "La pantalla de histórico recibe un volumen controlado incluso en ventanas largas.",
               "La Telemetría no conoce usuarios. Quien controla el acceso es el Backend."],
         "r": "apps/geopetro-telemetria/specs · software/apis/rest-monitoramento.md"},
        {"t": "Cómo se identifica la unidad",
         "c": "La web necesita un identificador estable. El contrato de recolección ya usaba el nombre de la unidad.",
         "d": "El registro se llama Unidade en todo el sistema. Web, REST y WebSocket usan el id numérico. MQTT e InfluxDB usan el nombre de la unidad como llave. El Backend traduce uno en otro antes de consultar la Telemetría.",
         "q": ["El Front trabaja con un único identificador.",
               "Cambiar el nombre de una unidad parte la serie histórica en dos. Es el riesgo de mayor costo registrado (RN-018)."],
         "r": "RN-018 · RN-119 · software/backend/braserv-core.md §9"},
        {"t": "Desktop como agente de borde dirigido por configuración",
         "c": "Cinco magnitudes fijas en el código impedían instrumentar equipos que no fueran taladros.",
         "d": "Cada unidad tiene un documento de tarjetas con la conexión del PLC y la lista de tarjetas, cada una con tipo y dirección. Se edita solo en el Desktop, por ADMIN o SUPORTE, se guarda en el Backend con número de revisión, se entrega por el canal STOMP /cards y queda en caché en disco. Hay seis tipos cerrados. La lectura se hace en bloque, un rango del DB por ciclo.",
         "q": ["Instrumentar un equipo nuevo pasa a ser un registro, no un proyecto.",
               "Una unidad sin tarjetas no lee ni publica (RN-088).",
               "Dos ediciones simultáneas se rechazan por la revisión, con error 409.",
               "Al copiar de otra unidad, la IP del PLC no se copia."],
         "r": "negocio/requisitos/cards-configuraveis.md · software/apis/configuracao-sonda.md"},
        {"t": "Identidad estable de la tarjeta",
         "c": "El id de la tarjeta se vuelve tag en InfluxDB, con retención de 5 años. Un tag con valores libres degrada la base.",
         "d": "El id se genera con el formato TIPO_NN, nunca cambia y no se reutiliza. El nombre es solo una etiqueta de pantalla. La tarjeta no se elimina, se desactiva. El límite es de 100 tarjetas por unidad.",
         "q": ["La cantidad de tags en InfluxDB queda bajo control.",
               "Toda serie antigua sigue teniendo una tarjeta que explica qué mide."],
         "r": "RN-081 · RN-091 · software/mqtt/mqtt-telemetria.md §4"},
        {"t": "La calibración se queda en la estación",
         "c": "La geometría del peso y de la llave hidráulica se miden en campo, en la propia unidad.",
         "d": "La calibración de peso y torque queda en el computador de la unidad, en config/calibracao-cards.json, separada por el id de la tarjeta. El rango del transmisor queda en el documento de la unidad.",
         "q": ["Los valores medidos en campo no viajan por la red.",
               "Cambiar el computador exige rehacer o copiar la calibración."],
         "r": "negocio/requisitos/cards-configuraveis.md §10b"},
        {"t": "El servidor registra la alarma y la estación la señala",
         "c": "La supervisión y el cliente necesitan un histórico único. El equipo en la unidad necesita la alarma aun sin red.",
         "d": "El Backend es el único productor del histórico de alarmas. Evalúa los límites remotos sobre el canal de tiempo real. La alarma es la única parte del sistema orientada a eventos: cada episodio es una secuencia de solo inserciones. La estación tiene sus propios límites locales, funciona sin red y sin inicio de sesión, y no genera eventos.",
         "q": ["Existe una única fuente de verdad para el histórico de alarmas.",
               "Una unidad con el tiempo real caído, o una tarjeta invisible, no alarma en el servidor aunque publique por MQTT.",
               "La alarma local solo llega a la flota con la actualización automática del Desktop, que todavía no existe."],
         "r": "negocio/requisitos/alarmes.md · negocio/requisitos/configuracao-da-estacao.md"},
        {"t": "Configuración restringida, con sesión solo en memoria",
         "c": "Ajustar dirección, rack y slot exige estar en la unidad. Existe una credencial de servicio común a toda la flota.",
         "d": "Configurar exige ADMIN o SUPORTE autenticado en línea. La sesión vive en memoria y no se guarda en disco. Sin iniciar sesión, el Desktop sigue leyendo, publicando y alarmando.",
         "q": ["Ninguna credencial adicional queda guardada en el borde (SEC-011).",
               "Configurar una estación exige internet."],
         "r": "RN-086 · negocio/requisitos/configuracao-da-estacao.md §5"},
        {"t": "Despliegue separado por camino de datos",
         "c": "La ingesta escribe sin parar y recibe conexiones de las unidades. La parte web es intermitente y guarda el registro de usuarios.",
         "d": "Dos máquinas virtuales. La transaccional tiene Front, Core, Backend y MySQL. La de telemetría tiene Mosquitto, Telemetría e InfluxDB. También existe una alternativa en una sola máquina, con Caddy y TLS automático. Las bases MySQL se versionan con Flyway y se validan al arrancar.",
         "q": ["Una falla en la web no interrumpe la ingesta.",
               "Cada lado escala de forma independiente.",
               "InfluxDB queda junto al consumidor, así la escritura continua no cruza la red. Entre las máquinas solo pasa la consulta REST."],
         "r": "deploy/README.md · deploy/vm-unica/README.md"},
        {"t": "Arquitectura hexagonal por módulo",
         "c": "Core y Backend tienen varios dominios y dependen uno del otro por red.",
         "d": "Core y Backend son proyectos Maven con un módulo por dominio, organizados en puertos y adaptadores. La integración entre servicios pasa por puertos, como AcessoDoUsuarioPort y CatalogoDeUnidadesPort.",
         "q": ["Cambiar un adaptador, como el cliente HTTP del Core, no toca la regla de negocio.",
               "Las pruebas de dominio corren sin red."],
         "r": "software/backend/braserv-core.md §7 y §10"},
    ],
    "h_riscos": "3. Riesgos aceptados y pendientes",
    "riscos_intro": "Estos puntos son conocidos y fueron aceptados o están esperando una decisión.",
    "cab_riscos": ["Punto", "Efecto", "Situación"],
    "riscos": [
        ["Broker STOMP en memoria", "Con dos instancias del Backend, el tiempo real no pasa de una a la otra.", "Aceptado mientras haya una sola instancia. Solución prevista: broker externo."],
        ["Broker MQTT sin autenticación", "Cualquier cliente en la red puede publicar en el tópico de telemetría.", "Pendiente (SEC-009)."],
        ["Nombre de la unidad como llave", "Cambiar el nombre parte la serie histórica.", "Riesgo aceptado (RN-018)."],
        ["Sin actualización automática del Desktop", "Las correcciones solo llegan a las unidades con una visita.", "Pendiente."],
        ["Búfer de contingencia MQTT", "Un broker caído por más de una hora descarta las lecturas más antiguas de la cola.", "Pendiente (P-07). El H2 local conserva el registro."],
        ["Token sin revocación individual", "Un token filtrado vale hasta que vence.", "Pendiente (SEC-008)."],
        ["Repositorios dentro de OneDrive", "La sincronización ya dañó un repositorio Git.", "Pendiente (DT-004)."],
    ],
    "h_onde": "Dónde profundizar",
    "onde": [
        ["Visión del sistema", "specs/SDD/software/system-overview.md"],
        ["Braserv-Core", "specs/SDD/software/backend/braserv-core.md"],
        ["Tiempo real", "specs/SDD/software/apis/websocket-realtime.md"],
        ["Telemetría MQTT", "specs/SDD/software/mqtt/mqtt-telemetria.md"],
        ["Tarjetas configurables", "specs/SDD/negocio/requisitos/cards-configuraveis.md"],
        ["Alarmas", "specs/SDD/negocio/requisitos/alarmes.md"],
        ["Despliegue", "deploy/README.md"],
        ["Reglas y pendientes", "specs/SDD/negocio/regras/business-rules.md · requisitos/open-questions.md"],
    ],
    "cab_onde": ["Tema", "Documento"],
}
